export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const SET_WALLET_ACCOUNT = "SET_WALLET_ACCOUNT"
export const SET_CONNECTED = "SET_CONNECTED"
export const GET_USER_PROFILE = "GET_USER_PROFILE"

export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST"
export const GET_COLLECTION = "GET_COLLECTION"
export const GET_MY_COLLECTIONS = "GET_MY_COLLECTIONS"
export const SET_PENDING = "SET_PENDING"
export const SET_SUCCESS = "SET_SUCCESS";

export const GET_ITEMS = "GET_ITEMS"